<a href="https://colab.research.google.com/github/BANZOM/MachingLearningStuffs/blob/main/NumPy_by_Aditya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **As on 22/08/2022**


In [2]:
import numpy as np

In [ ]:
arr1d= npy.array([1,2,3,4])

#prinring array
print(arr1d)

print(type(arr1d))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#2d array
arr2d= npy.array([ [1,2,3,4],[11,22,33,44] ])

print(arr2d)
type(arr2d)

[[ 1  2  3  4]
 [11 22 33 44]]


numpy.ndarray

In [ ]:
#check dimension of NumPy ndarray
print(arr1d.ndim)
print(arr2d.ndim)


1
2


In [ ]:
#check the size of the NumPy array
print(arr1d.size)
print(arr2d.size)

4
8


In [ ]:
#demintions of the NumPy array
print(arr1d.dtype)
print(arr2d.dtype)

int64
int64


In [ ]:
#check the shape of ndarray
print(arr1d.shape)
print(arr2d.shape)

(4,)
(2, 4)


In [ ]:
arr= npy.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
reArr= npy.reshape(arr,(5,4))
print(reArr)
reArr= npy.reshape(arr,(2,10))
print(reArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [ ]:
#Create metrics using python NumPy functions
#Syntax: np.ones(shape, dtype=None, order=‘C’)

oArr= npy.ones((4,4),dtype=int)
print(oArr)

#np.zeros(shape, dtype=None, order=‘C’)
oneArr= npy.zeros( (4,4) , dtype= int)
print(oneArr)

#np.empty(shape, dtype=None, order=‘C’)
emptyArr= npy.empty((3,3), dtype=bool)
print(emptyArr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[ True  True  True]
 [ True False False]
 [False False False]]


In [ ]:
#storing different datatypes in an array

multiDataTypeArray = npy.array([['id', 'name', 'percentage', 'pass or fail'], 
                         [101, 'Narendra', 80, 'pass'], 
                         [102, 'John', 75, 'pass'],
                         [103, 'Abraham',33, 'fail'],
                         [104, 'Oprah',52, 'pass']
                        ])
print(multiDataTypeArray)

[['id' 'name' 'percentage' 'pass or fail']
 ['101' 'Narendra' '80' 'pass']
 ['102' 'John' '75' 'pass']
 ['103' 'Abraham' '33' 'fail']
 ['104' 'Oprah' '52' 'pass']]


# NumPy Arithmetic Operations

In [ ]:
#creating a sample array for opetations
arr1 = npy.arange(1,10)
arr1 = arr1.reshape(3,3)

arr2 = npy.arange(11,20)
arr2 = arr2.reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
#addition of array
print(arr1+arr2)

#subtraction of array
print(arr1-arr2)
print(arr2-arr1)

#multiplication of matrix
print(arr1*arr2)


[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [ ]:
#Matrix Product of Two NumPy Array (matrix)
print(arr1@arr2)
# cab be done using @ operator
# or
#  by
# dot operator
print(arr1.dot(arr2) )

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


#NumPy Trigonometric Functions

In [ ]:
# pirnting sin value in degree and in radian
print("Sin")
print("In Degree: ", npy.sin(90))
print("In Radian: ", npy.sin( 90 * npy.pi/180 ))

print("Cos")
print("In Degree: ", npy.cos(90))
print("In Radian: ", npy.cos( 90 * npy.pi/180 ))


Sin
In Degree:  0.8939966636005579
In Radian:  1.0
Cos
In Degree:  -0.4480736161291701
In Radian:  6.123233995736766e-17


# 10 Dec 2k22




In [3]:
np.__version__

'1.21.6'

In [7]:
x = 4
print(type(x))
x = "four"
print(type(x))

<class 'int'>
<class 'str'>


list

In [12]:
x = list(range(1,3))
x

[1, 2]

In [18]:
# list of string
x = list( str(c) for c in range(1,11))
print( type(x[0]) )
x

<class 'str'>


['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [22]:
x = [1,"hi",True,0.8]
for i in x:
    print(type(i),"\n")

<class 'int'> 

<class 'str'> 

<class 'bool'> 

<class 'float'> 



creating a multi dimentional array from numpy array

In [28]:
x = np.array([ range(i, i+2) for i in [1,2,3]] ) 
print(x)

[[1 2]
 [2 3]
 [3 4]]


Integer array of length 10 consist of zeros

In [32]:
x = np.zeros(10, dtype="int")
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Creating a 3 x 5 array filled consist of 1

In [40]:
x = np.array( [(i,i,i,i,i) for i in [1,1,1]], dtype=float)
print(x)

# or

x = np.ones((3,5), dtype=float)
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


creating array of 3.14 of dimention 3x4

In [41]:
np.full((3,4), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

Create an array filled with a Linear sequence
Starting at 0, ending at 20, stepping by 2

In [50]:
print(np.arange(0,20,2))
for i in range(0,20,2):
    print(i)

[ 0  2  4  6  8 10 12 14 16 18]
0
2
4
6
8
10
12
14
16
18


creating an array of five values evenly spaces between 0 to 1

In [55]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])